"""
Correct tokens for the `other.d` file. Whitespace tokens are included.
"""
from pygments.token import Token

CORRECT_TOKENS = [
    (Token.Name.Builtin.Other, 'LeGo_Init'),
    (Token.Punctuation, '('),
    (Token.Name, 'LeGo_Focusname'),
    (Token.Punctuation, ')'),
    (Token.Punctuation, ';'),
    (Token.Text.Whitespace, '\n'),
    (Token.Keyword.Declaration, 'func'),
    (Token.Text.Whitespace, ' '),
    (Token.Keyword.Type, 'void'),
    (Token.Text.Whitespace, ' '),
    (Token.Name.Function, 'MEM_SendToSpy'),
    (Token.Punctuation, '('),
    (Token.Keyword.Declaration, 'var'),
    (Token.Text.Whitespace, ' '),
    (Token.Keyword.Type, 'int'),
    (Token.Text.Whitespace, ' '),
    (Token.Name, 'errorType'),
    (Token.Punctuation, ','),
    (Token.Text.Whitespace, ' '),
    (Token.Keyword.Declaration, 'var'),
    (Token.Text.Whitespace, ' '),
    (Token.Keyword.Type, 'string'),
    (Token.Text.Whitespace, ' '),
    (Token.Name, 'text'),
    (Token.Punctuation, ')'),
    (Token.Text.Whitespace, ' '),
    (Token.Punctuation, '{'),
    (Token.Punctuation, '};'),
    (Token.Text.Whitespace, '\n'),
    (Token.Name.Builtin.Other, 'MEM_SendToSpy'),
    (Token.Punctuation, '('),
    (Token.Literal.Number.Integer, '1'),
    (Token.Punctuation, ','),
    (Token.Text.Whitespace, ' '),
    (Token.Literal.String, '"a"'),
    (Token.Punctuation, ')'),
    (Token.Punctuation, ';'),
    (Token.Text.Whitespace, '\n'),
    (Token.Name.Builtin.Other, 'CALL_TEST_WORKING'),
    (Token.Punctuation, '('),
    (Token.Literal.Number.Integer, '111'),
    (Token.Punctuation, ')'),
    (Token.Punctuation, ';'),
    (Token.Text.Whitespace, '\n'),
    (Token.Name, 'call_test_notworking'),
    (Token.Punctuation, '('),
    (Token.Literal.Number.Integer, '222'),
    (Token.Punctuation, ')'),
    (Token.Punctuation, ';'),
    (Token.Text.Whitespace, '\n'),
]
