"""
Correct tokens for the `var.d` file. Whitespace tokens are included.
"""
from pygments.token import Token

CORRECT_TOKENS = [
    (Token.Keyword.Declaration, "func"),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Type, "string"),
    (Token.Text.Whitespace, " "),
    (Token.Name.Function, "Str_Format"),
    (Token.Punctuation, "("),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Declaration, "var"),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Type, "string"),
    (Token.Text.Whitespace, " "),
    (Token.Name, "format"),
    (Token.Punctuation, ","),
    (Token.Text.Whitespace, " "),
    (Token.Punctuation, "."),
    (Token.Punctuation, "."),
    (Token.Punctuation, "."),
    (Token.Text.Whitespace, " "),
    (Token.Punctuation, ")"),
    (Token.Text.Whitespace, " "),
    (Token.Punctuation, "{"),
    (Token.Punctuation, "};"),
    (Token.Text.Whitespace, "\n"),
    (Token.Keyword.Declaration, "func"),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Type, "string"),
    (Token.Text.Whitespace, " "),
    (Token.Name.Function, "Str_GetLocalizedString"),
    (Token.Punctuation, "("),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Declaration, "var"),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Type, "string"),
    (Token.Text.Whitespace, " "),
    (Token.Name, "russian"),
    (Token.Punctuation, ","),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Declaration, "var"),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Type, "string"),
    (Token.Text.Whitespace, " "),
    (Token.Name, "english"),
    (Token.Punctuation, ","),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Declaration, "var"),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Type, "string"),
    (Token.Text.Whitespace, " "),
    (Token.Name, "german"),
    (Token.Punctuation, ","),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Declaration, "var"),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Type, "string"),
    (Token.Text.Whitespace, " "),
    (Token.Name, "polish"),
    (Token.Text.Whitespace, " "),
    (Token.Punctuation, ")"),
    (Token.Text.Whitespace, " "),
    (Token.Punctuation, "{"),
    (Token.Punctuation, "};"),
    (Token.Text.Whitespace, "\n"),
    (Token.Keyword.Declaration, "func"),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Type, "string"),
    (Token.Text.Whitespace, " "),
    (Token.Name.Function, "Str_GetLocalizedStringEx"),
    (Token.Punctuation, "("),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Declaration, "var"),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Type, "string"),
    (Token.Text.Whitespace, " "),
    (Token.Name, "russian"),
    (Token.Punctuation, ","),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Declaration, "var"),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Type, "string"),
    (Token.Text.Whitespace, " "),
    (Token.Name, "english"),
    (Token.Punctuation, ","),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Declaration, "var"),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Type, "string"),
    (Token.Text.Whitespace, " "),
    (Token.Name, "german"),
    (Token.Punctuation, ","),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Declaration, "var"),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Type, "string"),
    (Token.Text.Whitespace, " "),
    (Token.Name, "polish"),
    (Token.Punctuation, ","),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Declaration, "var"),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Type, "string"),
    (Token.Text.Whitespace, " "),
    (Token.Name, "romanian"),
    (Token.Punctuation, ","),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Declaration, "var"),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Type, "string"),
    (Token.Text.Whitespace, " "),
    (Token.Name, "italian"),
    (Token.Punctuation, ","),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Declaration, "var"),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Type, "string"),
    (Token.Text.Whitespace, " "),
    (Token.Name, "czech"),
    (Token.Punctuation, ","),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Declaration, "var"),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Type, "string"),
    (Token.Text.Whitespace, " "),
    (Token.Name, "spanish"),
    (Token.Text.Whitespace, " "),
    (Token.Punctuation, ")"),
    (Token.Text.Whitespace, " "),
    (Token.Punctuation, "{"),
    (Token.Punctuation, "};"),
    (Token.Text.Whitespace, "\n"),
    (Token.Keyword.Declaration, "func"),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Type, "string"),
    (Token.Text.Whitespace, " "),
    (Token.Name.Function, "Str_UTF8_to_ANSI"),
    (Token.Punctuation, "("),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Declaration, "var"),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Type, "string"),
    (Token.Text.Whitespace, " "),
    (Token.Name, "utf8"),
    (Token.Punctuation, ","),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Declaration, "var"),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Type, "int"),
    (Token.Text.Whitespace, " "),
    (Token.Name, "codePage"),
    (Token.Text.Whitespace, " "),
    (Token.Punctuation, ")"),
    (Token.Text.Whitespace, " "),
    (Token.Punctuation, "{"),
    (Token.Punctuation, "};"),
    (Token.Text.Whitespace, "\n"),
    (Token.Keyword.Declaration, "func"),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Type, "int"),
    (Token.Text.Whitespace, " "),
    (Token.Name.Function, "Str_GetCurrentCP"),
    (Token.Punctuation, "("),
    (Token.Punctuation, ")"),
    (Token.Text.Whitespace, " "),
    (Token.Punctuation, "{"),
    (Token.Punctuation, "};"),
    (Token.Text.Whitespace, "\n"),
    (Token.Keyword.Declaration, "func"),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Type, "int"),
    (Token.Text.Whitespace, " "),
    (Token.Name.Function, "Str_GetLength"),
    (Token.Punctuation, "("),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Declaration, "var"),
    (Token.Text.Whitespace, " "),
    (Token.Keyword.Type, "int"),
    (Token.Text.Whitespace, " "),
    (Token.Name, "str"),
    (Token.Text.Whitespace, " "),
    (Token.Punctuation, ")"),
    (Token.Text.Whitespace, " "),
    (Token.Punctuation, "{"),
    (Token.Punctuation, "};"),
    (Token.Text.Whitespace, "\n"),
]
